### ISSUE TITLE
Unable to login to gitlab registry

### ISSUE THREAD

**Issue by timvol** [m1pl/semantic-release-helm#23]
I'm trying to get it working with gitlab, but failing while logging in:

```
[9:38:30 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Could not login to registry. Wrong credentials?
    at /usr/local/lib/node_modules/semantic-release-helm/node_modules/aggregate-error/index.js:23:11
    at Array.map (<anonymous>)
    at new AggregateError (/usr/local/lib/node_modules/semantic-release-helm/node_modules/aggregate-error/index.js:13:24)
    at module.exports (/usr/local/lib/node_modules/semantic-release-helm/lib/verifyConditions.js:37:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async verifyConditions (/usr/local/lib/node_modules/semantic-release-helm/index.js:9:5)
    at async validator (/usr/local/lib/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /usr/local/lib/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /usr/local/lib/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async Object.pluginsConf.<computed> [as verifyConditions] (/usr/local/lib/node_modules/semantic-release/lib/plugins/index.js:80:11) {
  pluginName: 'semantic-release-helm'
}
[9:38:30 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with ENOENT: helm registry login --username gitlab-ci-token --password-stdin some.gitlab.server
```

My .releaserc is the following:

```
{
    "branches": [
        {
            "name": "semanticrelease",
            "prerelease": false
        }],
    "plugins": [
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        "@semantic-release/changelog",
        "@semantic-release/gitlab",
        [ "semantic-release-helm",
            {
                chartPath: '.',
                registry: 'some.gitlab.server/api/v4/projects/349/packages/helm/stable'
            }
        ]
    ],
    "release": {
        "extends": "@semantic-release/gitlab-config",
        "prepare": [
          "@semantic-release/changelog",
          {
            "path": "@semantic-release/git",
            "assets": [
              "CHANGELOG.md"
            ]
          }
        ]
    }
}
```

And my gitlab-ci.yml looks like:

```
Release:
  image: aplyca/semantic-release
  script:
    - npm i -g semantic-release-helm
    - export REGISTRY_USERNAME=gitlab-ci-token
    - export REGISTRY_PASSWORD=glpat-something-BtHZ9gJi
    - semantic-release --repository-url=$CI_PROJECT_URL
```

The token/password used has all possible permissions, but fails. When I manually logging in to the registry using `helm registry login some.gitlab.server` with exactly the same credentials, it returns "Login Succeeded". Any ideas what I'm doing wrong here?

PS: Yes, I've hard-coded the REGISTRY_PASSWORD variable at the moment to make sure it's using the correct, working token.

**Comment by timvol** [comment]
Using helm3-version that also supports helm >= 3.7.0
