### ISSUE TITLE
Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead

### ISSUE THREAD

**Issue by mtusseau** [m1pl/semantic-release-helm#8]
The recent upgrade 2.0.X produces this error with node 14:

```
An error occurred while running semantic-release: Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.
    at Object.safeLoad (/usr/local/lib/node_modules/semantic-release-helm/node_modules/js-yaml/index.js:10:11)
    at module.exports (/usr/local/lib/node_modules/semantic-release-helm/lib/prepare.js:15:27)
    at async prepare (/usr/local/lib/node_modules/semantic-release-helm/index.js:18:5)
    at async validator (/usr/local/lib/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /usr/local/lib/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at async next (/usr/local/lib/node_modules/semantic-release/node_modules/p-reduce/index.js:16:18) {
  pluginName: 'semantic-release-helm'
}
Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.
    at Object.safeLoad (/usr/local/lib/node_modules/semantic-release-helm/node_modules/js-yaml/index.js:10:11)
    at module.exports (/usr/local/lib/node_modules/semantic-release-helm/lib/prepare.js:15:27)
    at async prepare (/usr/local/lib/node_modules/semantic-release-helm/index.js:18:5)
    at async validator (/usr/local/lib/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /usr/local/lib/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at async next (/usr/local/lib/node_modules/semantic-release/node_modules/p-reduce/index.js:16:18) {
  pluginName: 'semantic-release-helm'
}
```

**Comment by m1pl** [comment]
Version 2.0.2 with a fix should be available shortly. Thank you for the report.
